### PR TITLE
Revert MCKIN-8730 MCKIN-8714 MCKIN-8418

### PR DESCRIPTION
**Pull request by Agrendalath**
This reverts MCKIN-8730 MCKIN-8714 MCKIN-8418.

### CODE REVIEW

**Comment by UmanShahzad** [comment]
Only skimmed through this, but I think in general we should be good considering we were the only contributors on this repo ever since the optimization.

**Comment by Agrendalath** [comment]
@UmanShahzad, thanks for looking at this so quickly!
I wanted to leave a note here that I manually reverted reversion of `StudentSocialEngagementScore` fields and migrations here: c31ee62929c381d0cc841cd134a18591d302175e, so there would be no need for reverting migrations.

**Comment by UmanShahzad** [comment]
@Agrendalath Yep noticed that, it's a good idea. I'll be checking this out soon.

**Comment by UmanShahzad** [comment]
But you basically have my :+1: @Agrendalath .

**Review by UmanShahzad — APPROVED** [review]
:+1:

- [x] I tested this: Reverts the past few commits only. Migrations are kept since they only add fields that can have sane defaults if not filled.
- [x] I read through the code
- [x] I checked for accessibility issues
- [x] Includes documentation

**Pull request merged**
